---
- name: Workstation Setup
  hosts: localhost
  tasks:
  - name: Configure DNF
    ansible.builtin.blockinfile:
      backup: true
      block: |
        install_weak_deps=False
        defaultyes=True
        max_parallel_downloads=10
      path: /etc/dnf/dnf.conf
    become: True

  - name: Install Packages
    import_tasks: tasks/dnf-packages-installation.yml
    become: True

  - name: Install Development Packages
    import_tasks: tasks/development-setup.yml

  - name: Setup GO env
    import_tasks: tasks/go-env-setup.yml

  - name: Setup Flatpak
    import_tasks: tasks/flatpak-setup.yml

  - name: Install Flatpak Apps
    import_tasks: tasks/flatpak-apps.yml

