- name: Installing development packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
    - golang
    - rust
    - cargo
    - rust-doc
    - yamllint
    - '@Container Management'
  register: installed
