- name: Instaling required packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: latest
  loop:
  # gui core server/application
    - xorg-x11-server-Xorg
    - xorg-x11-xinit
    - xrandr
    - i3-gaps
  # utilties
    - redshift
    - rofi
    - kitty
    - flatpak
    - tmux
    - neovim
